# Data Conversion to a Python-Compatible Pandas dataframe

In [7]:
# Import needed packages 

import numpy as np
import pandas as pd

from mne.externals.pymatreader import read_mat

In [8]:
# Load Raw Data

raw = read_mat('/Users/anastasiakuzmich/Downloads/Marios_data/Data.mat')
raw.keys()

dict_keys(['__header__', '__version__', '__globals__', 'CarData', 'FaceData', 'CarData2', 'FaceData2', 'AllData', 'AllData2', 'stiml', 'stim'])

### 1. EEG Signals

In [9]:
# Access file

data = raw['AllData']
data.shape

(60, 333900)

In [12]:
# Convert to pandas

X = pd.DataFrame(data=data.T)
X

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
0,4.101563,0.488281,-1.074219,-1.074219,-0.781250,-1.220703,-1.220703,-1.220703,-0.585938,-1.171875,...,-0.146484,-0.634766,-4.443360,0.585938,0.341797,0.000000,-0.341797,-0.830078,-1.220703,-0.878906
1,4.296875,-0.244141,-1.220703,-0.927734,-0.634766,-1.318360,-1.269531,-1.318360,-0.292969,-1.074219,...,-0.341797,-0.830078,-4.443360,0.341797,0.048828,-0.195313,-0.488281,-1.074219,-1.367188,-1.025391
2,3.417969,-0.781250,-1.171875,-0.439453,-0.439453,-1.123047,-1.123047,-1.220703,-0.146484,-0.878906,...,-0.537109,-0.830078,-4.052735,0.341797,0.048828,-0.244141,-0.488281,-1.025391,-1.025391,-0.732422
3,1.953125,-0.732422,-0.878906,-0.048828,-0.146484,-0.830078,-0.927734,-1.025391,0.048828,-0.634766,...,-0.488281,-0.585938,-3.466797,0.634766,0.390625,-0.097656,-0.292969,-0.781250,-0.585938,-0.341797
4,1.123047,-0.341797,-0.585938,-0.244141,0.000000,-0.488281,-0.976563,-1.025391,-0.048828,-0.585938,...,-0.292969,-0.341797,-2.929688,1.318360,1.074219,0.146484,0.000000,-0.439453,-0.292969,-0.097656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333895,0.439453,-0.439453,-0.585938,0.195313,0.732422,0.048828,-0.537109,-0.439453,-0.341797,0.390625,...,0.000000,-0.439453,-1.123047,-0.634766,-0.830078,-0.878906,-1.025391,-0.976563,-2.001953,-1.855469
333896,0.390625,-0.537109,-0.537109,0.000000,0.781250,0.000000,-0.683594,-0.537109,-0.341797,0.341797,...,-0.097656,-0.390625,-1.123047,-0.781250,-0.927734,-1.074219,-0.976563,-0.976563,-2.001953,-1.953125
333897,0.927734,-0.830078,-0.683594,-0.195313,0.732422,-0.097656,-0.781250,-0.634766,-0.390625,0.048828,...,-0.146484,-0.341797,-1.220703,-0.878906,-1.025391,-1.171875,-1.025391,-0.927734,-2.050781,-2.099610
333898,1.708985,-1.171875,-0.976563,-0.439453,0.634766,-0.341797,-0.830078,-0.732422,-0.390625,-0.048828,...,-0.146484,-0.341797,-1.269531,-1.025391,-1.220703,-1.220703,-0.976563,-0.927734,-2.294922,-2.148438
333899,2.294922,-1.318360,-1.171875,-0.585938,0.537109,-0.537109,-0.927734,-0.830078,-0.244141,-0.195313,...,-0.097656,-0.244141,-1.220703,-1.123047,-1.318360,-1.318360,-0.976563,-0.878906,-2.392578,-2.197266

In [13]:
# Save as a pandas dataframe

X.to_pickle("data.pkl")

### 2. Events

In [23]:
# Face vs Car = Task

a = raw['stim']

print(a)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]

In [24]:
# Coherence + Face = Both

b = raw['stiml']

print(b)

[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  5  5  5  5  5  5  5  5  5
  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5
  5  5  5  5  5  5  5  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6
  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  6  7
  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7
  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  8  8  8  8  8  8  8  8  8
  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8
  8  8  8  8  8  8  8  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9
  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9  9 10 10
 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 10 10 10 10 10 10 10 10 10 10 10 10 10 11 11 11 11 11 11 11 11 11 11 11
 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11
 11 11 11 11 11 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12
 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12]

In [25]:
# Coherence

c = raw['stiml']

c = np.where(c==7, 1, c)
c = np.where(c==8, 2, c)
c = np.where(c==9, 3, c)
c = np.where(c==10, 4, c)
c = np.where(c==11, 5, c)
c = np.where(c==12, 6, c)

c

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6], dtype=uint8)

In [29]:
# Join structures

data = {'Task': a, 'Coherence': c, 'Both' : b}

In [30]:
# Create dataframe

events = pd.DataFrame(data)
events

     Task  Coherence  Both
0       1          1     1
1       1          1     1
2       1          1     1
3       1          1     1
4       1          1     1
..    ...        ...   ...
472     2          6    12
473     2          6    12
474     2          6    12
475     2          6    12
476     2          6    12

[477 rows x 3 columns]

In [ ]:
# Save as a pandas dataframe

Y.to_pickle("events.pkl")